spring.data.mongodb.uri=mongodb+srv://dtufan38_db:Tufandas%40464849@cluster0.vguw13b.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation = true


#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=mongodb+srv://dtufan38_db:<db_password>@cluster0.vguw13b.mongodb.net/?appName=Cluster0
